version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: hw02_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: hw02_app
    restart: always
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postgres:567234@db:5432/hw02
    ports:
      - "8000:8000"

volumes:
  pg_data:
